{% set name = "euporie" %}
{% set version = "2.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/euporie-{{ version }}.tar.gz
  sha256: 801233f34ffffa875c0c09cf476e8a9f63990ada98197cb8ac5526e297f9c976

build:
  entry_points:
    - euporie = euporie.core.__main__:main
    - euporie-console = euporie.console.__main__:main
    - euporie-notebook = euporie.notebook.__main__:main
    - euporie-preview = euporie.preview.__main__:main
    - euporie-hub = euporie.hub.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - jupytext >=1.14.0
    - python >=3.8
    - prompt-toolkit >=3.0.36,<3.1.dev0
    - pygments >=2.11,<3.dev0
    - nbformat >=5.0,<6.dev0
    - jupyter_client >=7.1
    - aenum >=3.1,<4.dev0,<=3.1.12
    - typing-extensions >=4.5,<5.dev0
    - python-fastjsonschema >=2.15,<3.dev0
    - platformdirs >=3.5,<4.dev0
    - pyperclip >=1.8,<2.dev0
    - imagesize >=1.3,<2.dev0
    - markdown-it-py >=2.1.0,<2.2.dev0
    - linkify-it-py >=1.0,<2.dev0
    - mdit-py-plugins >=0.3.0,<0.4.dev0
    - flatlatex >=0.15,<1.dev0
    - timg >=1.1.6,<1.2.dev0
    - pillow >=9.0,<10.dev0
    - sixelcrop >=0.1.6,<0.2.dev0
    - universal_pathlib >=0.2.1,<0.3.dev0
    - fsspec >=2022.12.0

test:
  imports:
    - euporie
  commands:
    - pip check
    - euporie --help
    - euporie-console --help
    - euporie-notebook --help
    - euporie-preview --help
    - euporie-hub --help
  requires:
    - pip
    - aiohttp
    - asyncssh
    - requests

about:
  home: https://github.com/joouha/euporie
  summary: Euporie is a suite of terminal applications for interacting with Jupyter kernels
  dev_url: https://github.com/joouha/euporie
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
    - joouha
