{% set name = "euporie" %}
{% set version = "2.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/euporie-{{ version }}.tar.gz
  sha256: 3dbef1c14cbe5e24de5cf77dc50e1c47109c74ff404a7852c3fac15449d6af48

build:
  number: 0
  noarch: python
  entry_points:
    - euporie = euporie.core.__main__:main
    - euporie-console = euporie.console.__main__:main
    - euporie-notebook = euporie.notebook.__main__:main
    - euporie-preview = euporie.preview.__main__:main
    - euporie-hub = euporie.hub.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8,<4.0
    - hatchling
  run:
    - aenum <=3.1.12,>=3.1
    - appdirs >=1.4,<2
    - aiohttp
    - requests
    - python-fastjsonschema >=2.15.3,<2.15.4
    - flatlatex >=0.15,<1
    - imagesize >=1.3.0,<1.4.0
    - jupyter_client >=7.1,<8
    - linkify-it-py >=1.0,<2
    - markdown-it-py ==2.1.0
    - mdit-py-plugins >=0.3,<0.4
    - nbformat >=5.1.3,<6
    - Pillow >=9.0,<10
    - prompt-toolkit >=3.0.27,<4
    - Pygments >=2.11.2,<2.12.0
    - pyperclip >=1.8,<2.0.0
    - python >=3.8,<4.0
    - timg >=1.1,<2
    - typing-extensions >=4.5,<4.6
    - universal_pathlib <0.0.24
    - sixelcrop
    - platformdirs >=3.5,<3.6

test:
  imports:
    - euporie.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/joouha/euporie
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Euporie is a text-based user interface for running and editing Jupyter notebooks
  description: |
    Euporie is a text-based user interface for running and editing 
    Jupyter notebooks
  doc_url: https://euporie.readthedocs.io/
  dev_url: https://github.com/joouha/euporie

extra:
  recipe-maintainers:
    - jan-janssen
    - joouha
