{% set name = "euporie" %}
{% set version = "1.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/euporie-{{ version }}.tar.gz
  sha256: 3a8bc788ff70147837af0667848d7810137b305f6b7f93b0d6d9318e3486f292

build:
  number: 0
  noarch: python
  entry_points:
    - euporie = euporie.app:App.launch
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - poetry
  run:
    - appdirs
    - aenum <4.0,>=3.1
    - flatlatex
    - jsonschema <5.0,>=4.4
    - jupyter_client <8.0,>=7.1
    - nbformat >=5.1.3,<6.0.0
    - pillow <10.0,>=9.0
    - prompt-toolkit >=3.0.18,<4.0.0
    - pyperclip >=1.8.2,<2.0.0
    - python >=3.6,<4.0
    - rich <12,>=11
    - imagesize
    - timg

test:
  imports:
    - euporie
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/joouha/euporie
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Euporie is a text-based user interface for running and editing Jupyter notebooks
  description: |
    Euporie is a text-based user interface for running and editing 
    Jupyter notebooks
  doc_url: https://euporie.readthedocs.io/
  dev_url: https://github.com/joouha/euporie

extra:
  recipe-maintainers:
    - jan-janssen
