{% set name = "euporie" %}
{% set version = "2.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/euporie-{{ version }}.tar.gz
  sha256: 45b86b77a816f9d2f59cefe1d22525655a0fb2ae6d593710c9035f257481c476

build:
  entry_points:
    - euporie = euporie.core.__main__:main
    - euporie-console = euporie.console.__main__:main
    - euporie-notebook = euporie.notebook.__main__:main
    - euporie-preview = euporie.preview.__main__:main
    - euporie-hub = euporie.hub.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - prompt-toolkit >=3.0.36,<3.1.dev0
    - pygments >=2.11,<3.dev0
    - nbformat >=5.0,<6.dev0
    - jupyter_client >=7.1
    - aenum >=3.1,<4.dev0,<=3.1.12
    - typing-extensions >=4.5,<5.dev0
    - python-fastjsonschema >=2.15,<3.dev0
    - platformdirs >=3.5,<4.dev0
    - pyperclip >=1.8,<2.dev0
    - imagesize >=1.3,<2.dev0
    - markdown-it-py >=2.1.0,<2.2.dev0
    - linkify-it-py >=1.0,<2.dev0
    - mdit-py-plugins >=0.3.0,<0.4.dev0
    - flatlatex >=0.15,<1.dev0
    - timg >=1.1,<2.dev0
    - pillow >=9.0,<10.dev0
    - sixelcrop >=0.1.3,<0.2.dev0
    - universal_pathlib <0.0.24
    - fsspec >=2022.8.0
    - aiohttp

test:
  imports:
    - euporie
  commands:
    - pip check
    - euporie --help
    - euporie-console --help
    - euporie-notebook --help
    - euporie-preview --help
    - euporie-hub --help
  requires:
    - pip

about:
  home: https://github.com/joouha/euporie
  summary: Euporie is a suite of terminal applications for interacting with Jupyter kernels
  dev_url: https://github.com/joouha/euporie
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
    - joouha
