{% set name = "euporie" %}
{% set version = "0.1.12" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/euporie-{{ version }}.tar.gz
  sha256: c5d77d31e9b2924c36b707c58520c5368482f7981d9c6695e9e0b15a995ec452

build:
  number: 0
  noarch: python
  entry_points:
    - euporie = euporie.app:App.launch
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - poetry
  run:
    - jsonschema >=3.2.0,<4.0.0
    - jupyter_client ==6.1.12
    - nbformat >=5.1.3,<6.0.0
    - pillow >=8.2.0,<9.0.0
    - prompt-toolkit >=3.0.18,<4.0.0
    - python >=3.6,<4.0
    - rich >=10.1.0,<11.0.0

test:
  imports:
    - euporie
    - euporie.libs.commonmark_extensions
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/joouha/euporie
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Euporie is a text-based user interface for running and editing Jupyter notebooks
  description: |
    Euporie is a text-based user interface for running and editing 
    Jupyter notebooks
  doc_url: https://github.com/joouha/euporie
  dev_url: https://github.com/joouha/euporie

extra:
  recipe-maintainers:
    - jan-janssen
