{% set name = "euporie" %}
{% set version = "1.4.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/euporie-{{ version }}.tar.gz
  sha256: b7531741290c0fbb77a1f97f21a564ff85fa58abfa293e50ea2acd6cbaf15940

build:
  number: 0
  noarch: python
  entry_points:
    - euporie = euporie.app:App.launch
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - poetry
  run:
    - appdirs
    - aenum <4.0,>=3.1
    - flatlatex
    - jsonschema <5.0,>=4.4
    - jupyter_client <8.0,>=7.1
    - nbformat >=5.1.3,<6.0.0
    - pillow <10.0,>=9.0
    - prompt-toolkit >=3.0.18,<4.0.0
    - pyperclip >=1.8.2,<2.0.0
    - python >=3.6,<4.0
    - rich <13.0.0,>=12.0.1
    - imagesize
    - timg
    - html2text
    - linkify
    - markdown-it-py

test:
  imports:
    - euporie
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/joouha/euporie
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Euporie is a text-based user interface for running and editing Jupyter notebooks
  description: |
    Euporie is a text-based user interface for running and editing 
    Jupyter notebooks
  doc_url: https://euporie.readthedocs.io/
  dev_url: https://github.com/joouha/euporie

extra:
  recipe-maintainers:
    - jan-janssen
